<?php

namespace BackOfficeBundle\Repository;

/**
 * DeplacementJourRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DeplacementJourRepository extends \Doctrine\ORM\EntityRepository
{
	
}
