<?php

/**
 * 
 * @author	Mathias C-D
 * @version	1.0.0
 */

namespace BackOfficeBundle\Repository;

/**
 * ServiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServiceRepository extends \Doctrine\ORM\EntityRepository
{
	
}
