<?php

namespace BackOfficeBundle\Repository;

/**
 * TypeDeplacementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeDeplacementRepository extends \Doctrine\ORM\EntityRepository
{
	
}
