<?php

namespace BackOfficeBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
	public function findAllThatMatchWith($reg) {
		return $this->getEntityManager()
					->getRepository("BackOfficeBundle:User")
					->createQueryBuilder("u")

					->where("u.nom LIKE :nom")
					->setParameter("nom", "%" . $reg . "%")
					->orderBy("u.nom", "ASC")
					->orderBy("u.prenom", "ASC")

					->getQuery()
					->getResult();
	}
}
