<?php

/**
 * Requêtes Ville
 * @author	Mathias C-D
 * @version	1.0.0
 */

namespace BackOfficeBundle\Repository;

/**
 * VilleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VilleRepository extends \Doctrine\ORM\EntityRepository
{
	public function getNbUsersPerCity() {
		return $this->getEntityManager()
					->createQueryBuilder()
					->select('v.ville, COUNT(u.id) AS nb')
					->from('BackOfficeBundle:User', 'u')
					->from('BackOfficeBundle:Ville', 'v')
					->where('IDENTITY(u.ville) = v.id')
					->groupBy("u.ville")

					->getQuery()
					->getResult();
	}
}
