web_service_homepage:
    path:     /
    defaults: { _controller: WebServiceBundle:Default:index }

web_service_getdep:
    path:     /trips/
    defaults: { _controller: WebServiceBundle:Default:TripsApi }

web_service_getdep_user:
    path:     /trips/{user}
    defaults: { _controller: WebServiceBundle:Default:TripsUserApi }

web_service_getdep_user_date:
    path:     /trips/{user}/{year}/{month}
    defaults: { _controller: WebServiceBundle:Default:TripsUserDateApi }

web_service_getuser:
    path:     /user/{user}
    defaults: { _controller: WebServiceBundle:Default:UserApi }
